version: "3.4"

networks:
  inner_net:

services:
  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./dev-prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - inner_net

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    user: "$UID:$GID"
    ports:
      - "9091:3000"
    networks:
      - inner_net

  mariadb:
    image: mariadb
    restart: always
    networks:
      - inner_net
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecretPassword
      MYSQL_DATABASE: WaystoneInn
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
