version: '3.4'

services:
  minitwit_be.api:
    image: jrusbjerg/twitbackend:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5000:443"