language: csharp
mono: none
dotnet: 6.0

addons:
  sonarcloud:
    organization: "jesperrusbjerg"
    token:
      secure: ${SONAR_TOKEN} # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
     
before_script:
- dotnet restore ".\Minitwit_BE\Minitwit_BE.sln"

script:
- dotnet build ".\Minitwit_BE\Minitwit_BE.sln" -c Release 
- sonar-scanner
#- dotnet test ".\Minitwit_BE\Minitwit_BE.sln" -c Release -v n


