language: minimal

before_install:
- openssl aes-256-cbc -K $encrypted_45f528406b86_key -iv $encrypted_45f528406b86_iv
  -in travis-rsa.enc -out travis-rsa -d
  - chmod 600 travis_rsa
  - mv travis_rsa ~/.ssh/id_rsa
  
  
stages:
  - deploy

jobs:
  include:
    - stage: deploy
      name: "deploy new version"
      install: skip
      # -o flag to get around "add ip to known hosts prompt"
      script: |
        ssh -o "StrictHostKeyChecking no" root@$138.68.69.204 \
        "ls"
