language: minimal

addons:
  sonarcloud:
    organization: "jesperrusbjerg"
    token:
      secure: iBtLvXuy6mCpm4I4O10mWa9FTupCUQY3+Xt97ojkwb/nrpc9jwSCuNnHuwHHonnilJXkB5TGs8ubOo+XUlY6JCAM6gSwz8AQDazG5gioSxN79yeWLaUV5aCs2ybhDn65fFiF8ytWPp9M1uelNP+MOvwgkcUHmh0hjS0MWzItO0vH6fRAqhAHFTgQX60E5qTg1MV8zLyMEnVrow6LOW1On68/eHYJl++APhm4Z5Et9Wa8GQDd6VjxbonBxQongrLQmsTuFUH0RAdIruEu5qxJjpkk/Yk10/WbJqf0Rk2y9Qd196rCyb2drtKwcwCVwxaHSDIe4TQ2QJRPnxpZoKQRJSy2rksqvSUN8I2ZO7akC6TyhFL46MQot2dvtoVszCVL1TuKXhIT7pH6EmtfcSSWPV2+JZKNjqp6+5t8DSeuInsLI5Py/BVU1wbUPRldhKdAZzQ4J8XgwPSH19w3vwERUpKjN2khXo3GbR/hdWE9AprK10iEO5+8WBlrMAo0R5F9mhuMYH3aIk57cjWcabAisWhh15UiQhMJgoYSObLtEvOR6dGWjJ0QzzbmObc74XT82oW9DzPzL4mMsMXtYKRCWqoWary5JsG8qPYOFARNf4Ma01WZuWH6MVV7bKFpS9o/ZhfrvC6C6WAX0Iq+lIz7752WAzwBuQW2U3cepXqLn+c= # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner

branches:
  only:
  - main

before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out /tmp/git_deploy_key -d
- chmod 600 /tmp/git_deploy_key
- echo 'echo ${SSH_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
- eval "$(ssh-agent -s)"
- DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/git_deploy_key </dev/null

install:
- docker --version

stages:
- docker_build
- deploy

jobs:
  include:
  - stage: docker_build
    name: build and push docker
    if: branch = "main"
    script:
    - echo "LOGIN"
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PSW
    - echo "BUILD"
    - docker build -t jrusbjerg/twitbackend -f Minitwit_BE/Minitwit_BE.Api/Dockerfile
      Minitwit_BE/.
    - echo "PUSH"
    - docker push jrusbjerg/twitbackend:latest
  - stage: deploy
    name: deploy new version
    if: branch = "main"
    install: skip
    script: "ssh -o \"StrictHostKeyChecking no\" ${MT_USER}@${MT_SERVER} \\\n\"docker-compose
      down && \\\ndocker-compose pull && \\\ndocker-compose rm -f && \\\ndocker-compose
      up -d && \\\nexit \" \n"
