language: csharp
solution: Minitwit_BE/Minitwit_BE.sln
# install:
#   - nuget restore solution-name.sln
#   - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - echo test

branches:
  only:
    - feature/travis-ci
