language: csharp
mono: none
dotnet: 6.0

addons:
  sonarcloud:
    organization: "jesperrusbjerg"
    token:
     secure: $SONAR_TOKEN
     
before_script:
- dotnet restore ".\Minitwit_BE\Minitwit_BE.sln"

script:
- dotnet build ".\Minitwit_BE\Minitwit_BE.sln" -c Release 
- sonar-scanner
#- dotnet test ".\Minitwit_BE\Minitwit_BE.sln" -c Release -v n


