version: '3.4'

services:
  minitwit_be.api:
    image: jrusbjerg/twitbackend
    ports:
      - "7000:80"
      - "7001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=toonage15
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Minitwit_BE.Api.pfx
    volumes:
      - ~/.aspnet/https:/https:ro