name: Docker Image CI

on:
  push:
    branches: [ feature/travis ]
  pull_request:
    branches: [ feature/travis ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: echo test
